### ISSUE TITLE
image is not displaying spherically

### ISSUE THREAD

**Issue by floscher** [miurahr/panoramaviewer#2]
I just tried out `./gradlew run` and what I got was a flat 2d image instead of the spherical display:
![360° image viewer window](https://user-images.githubusercontent.com/3904348/41227857-9956e1ce-6d76-11e8-8c6b-c162307f13d3.png)

Did I do something wrong, or is this a bug?

**Comment by miurahr** [comment]
Oh, I've committed wrong code.
```
 -if(!Mapillary360ImageDisplay.is360Image(getClass().getResourceAsStream(imageFileName))) {
 +if(Mapillary360ImageDisplay.is360Image(getClass().getResourceAsStream(imageFileName))) {
```

**Comment by miurahr** [comment]
Thank you for feedback! Fixed now.

**Comment by floscher** [comment]
Thanks for fixing the issue, the image is now no longer distorted. It's really great to see work being done in this area.

However the image now seems to be displayed mirrored:
![360° image viewer vs flat 2d image](https://user-images.githubusercontent.com/3904348/41290933-98da13e6-6e4e-11e8-8478-ea814a67ba58.png)
(above is the viewer window, below the image as it appears in a normal "flat" image viewer)

**Comment by miurahr** [comment]
Oh, it seems not only mirrored, also it has some errors.

I think this approach is failed . We need to find better way.

**Comment by floscher** [comment]
What kind of errors do you mean? Apart from the mirroring I think the viewer displays the image rather well.

**Comment by miurahr** [comment]
![screenshot from 2018-06-13 00-23-20](https://user-images.githubusercontent.com/123720/41300150-03a24a76-6ea0-11e8-97f9-105668d87a06.png)

This part show distortion

**Comment by floscher** [comment]
That's not a screenshot of your image viewer, this was only the 360° image as displayed by a 2d image viewer (simply as a flat rectangle).
I only pasted it here to see that the source image is flipped. Only the top image is from your image viewer and shows without any distortion.

**Comment by miurahr** [comment]
Thanks for your explanation. Got it.
I'd like also to try another approach in addition to current approach with fixes.
